//
//  Welcome.swift
//  AIEduation
//
//  Created by Ben Lawrence on 14/11/2025.
//

import SwiftUI

struct WelcomeView: View {
  @AppStorage("hasSeenWelcome") var hasSeenWelcome: Bool = false
  @Environment(\.dismiss) private var dismiss
  @State private var currentPage: Int = 1

  var body: some View {
    VStack {
      if currentPage == 1 {
        WelcomePage1()
      } else if currentPage == 2 {
        WelcomePage2()
      }

      Button(action: {
        if currentPage < 2 {
          currentPage += 1
        } else {
          hasSeenWelcome = true
          dismiss()
        }
      }) {
        Text(currentPage < 2 ? "Next" : "Let's Go!")
          .font(.headline)
          .padding()
      }
      .tint(.accentColor)
      .buttonStyle(.glassProminent)
      .buttonSizing(.flexible)
    }
    .padding()
  }
}

struct WelcomePage1: View {
  @AppStorage("hasSeenWelcome") var hasSeenWelcome: Bool = false

  @Environment(\.dismiss) private var dismiss
  @Environment(\.horizontalSizeClass) private var horizontalSizeClass

  var body: some View {
    VStack {
      WelcomeComponents.WelcomePageHeader(
        title: "Welcome to AIEducation",
        subtitle: "Your gateway to learning about AI and its applications.",
        imageName: "graduationcap.fill",
      )

      Spacer()

      VStack(alignment: .leading) {
        WelcomeComponents.WelcomePoint(
          title: "Explore AI Concepts",
          description:
            "Dive into the fundamentals of artificial intelligence, machine learning, and deep learning.",
          imageName: "brain.head.profile"
        )

        WelcomeComponents.WelcomePoint(
          title: "Hands-on Lessons",
          description:
            "Engage with interactive lessons that make learning AI fun and practical.",
          imageName: "book.fill"
        )

        WelcomeComponents.WelcomePoint(
          title: "Powered by Apple Intelligence",
          description:
            "Experience the cutting-edge capabilities of Apple Intelligence to enhance your learning journey.",
          imageName: "apple.intelligence"
        )
      }
    }
  }
}

struct WelcomePage2: View {
  var body: some View {
    VStack {
      WelcomeComponents.WelcomePageHeader(
        title: "Just a quick heads up!",
        subtitle: "lorem ipsum dolor sit amet",
        imageName: "exclamationmark.triangle.fill",
      )

      Spacer()

      Text(
        "Some of the contents in this app are generated using AI technologies. The outputs of these technologies may not always be accurate. Content generated by AI will be clearly marked with the highlight shown below. Where possible prompts used to generate the content will also be provided."
      )
      .padding(.bottom)

      HStack(spacing: 40) {
        VStack {
          Text("Real Image")
            .font(.headline)

          if let url = Bundle.main.url(
            forResource: "E7533C1F-2A1E-4270-9023-E74C0C4D18D8",
            withExtension: "jpeg"
          ) {
            Image(uiImage: UIImage(contentsOfFile: url.path)!)
              .resizable()
              .scaledToFill()
              .frame(width: 150, height: 150)
              .clipped()
              .cornerRadius(12)
          }
        }

        VStack {
          Text("AI Generated Image")
            .font(.headline)

          if let url = Bundle.main.url(
            forResource: "AIExample",
            withExtension: "jpg"
          ) {
            Image(uiImage: UIImage(contentsOfFile: url.path)!)
              .resizable()
              .scaledToFit()
              .frame(width: 150, height: 150)
              .cornerRadius(12)
              .intelligence(in: .rect(cornerRadius: 12), spread: 4)
          }
        }
      }

      Spacer()
    }
  }
}

struct WelcomeComponents {
  @ViewBuilder
  static func WelcomePoint(
    title: String,
    description: String,
    imageName: String
  ) -> some View {
    HStack {
      Image(systemName: imageName)
        .resizable()
        .scaledToFit()
        .frame(width: 40, height: 40)
        .foregroundStyle(.green.gradient)

      VStack(alignment: .leading, spacing: 4) {
        Text(title)
          .font(.title3)
          .fontWeight(.bold)

        Text(description)
          .font(.body)
          .foregroundStyle(.secondary)
          .fixedSize(horizontal: false, vertical: true)
          .lineLimit(nil)
      }
      .padding()
    }
  }

  @ViewBuilder
  static func WelcomePageHeader(
    title: String,
    subtitle: String,
    imageName: String,
    imageColor: Color = .accentColor
  ) -> some View {
    VStack(spacing: 16) {
      Image(systemName: imageName)
        .font(.system(size: 72))
        .foregroundStyle(.white)
        .frame(width: 114, height: 114)
        .background(imageColor.gradient)
        .cornerRadius(20)
        .padding(.bottom, 5)

      VStack {
        Text(title)
          .font(.title)
          .fontWeight(.bold)

        Text(subtitle)
          .font(.subheadline)
          .foregroundColor(.secondary)
          .multilineTextAlignment(.center)
          .fixedSize(horizontal: false, vertical: true)
      }
    }
    .padding()
  }
}
