//
//  listofcredits.swift
//  AIEduation
//
//  Created by Ben Lawrence on 05/11/2025.
//

/// Nature Images https://archive.org/details/various-nature-images-zip
/// cat https://unsplash.com/photos/silver-tabby-kitten-on-floor-7AIDE8PrvA0
/// driving - recorded by me (Ben Lawrence)
/// TrainingData - photo by me (Ben Lawrence)
/// AIExample - Generated by me (Ben Lawrence) using Image Playground
