// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AIEducation",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "AIEducation",
            targets: ["AppModule"],
            bundleIdentifier: "com.bentheminernz.AIEduation",
            teamIdentifier: "4TD3JXVDW7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .carrot),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibraryAdd(purposeString: "AI Education needs access in order to save images."),
                .contacts(purposeString: "Let the AI Model access your contacts.")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/appstefan/HighlightSwift", "1.0.9"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "HighlightSwift", package: "highlightswift")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)